import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Bootcamp Bank",
  description: "Generated by bootcamp",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center justify-between min-h-screen">
        <Navbar />
        <main className="flex-grow w-full max-w-6xl py-6">{children}</main>
      </body>
    </html>
  );
}
